import apnaImg from "../../assets/certificates/apna_top_creator.jpg";
import googleImg from "../../assets/certificates/google_digital_unlocked.jpg";
import microsoftImg from "../../assets/certificates/microsoft_certified.jpg";
import adobeImg from "../../assets/certificates/adobe_photoshop.jpg";
import autodeskImg from "../../assets/certificates/autodesk_autocad.webp";
import eccouncilImg from "../../assets/certificates/eccouncil_codered.png";
import redhatImg from "../../assets/certificates/redhat_rhcsa.png";

export const CERTIFICATES = [
  {
    id: "APNA-JOB-2025-TE",
    title: "India's Top Job Creator 2025",
    partner: "Apna Hiring",
    category: "Industry & Hiring",
    image: apnaImg,
    fallbackUrl: "https://thirdeyeclasses.com/wp-content/uploads/2025/03/19-1024x724.jpg",
    issuer: "Apna - India's Leading Hiring Platform",
    description: "Honored as a foremost job creator for outstanding recruitment enablement and corporate campus placement records.",
    skills: "Corporate Placements, Technical Talent Sourcing, Career Readiness",
    impact: "Over 25,000+ student careers facilitated across 500+ top enterprises.",
  },
  {
    id: "NZR-AS3-QUK",
    title: "The Fundamentals of Digital Marketing",
    partner: "Google",
    category: "Global Tech",
    image: googleImg,
    fallbackUrl: "https://thirdeyeclasses.com/wp-content/uploads/2025/03/18-scaled.jpg",
    issuer: "Google EMEA & Interactive Advertising Bureau Europe",
    description: "Official credential accredited by Google Digital Unlocked and The Open University covering full-funnel digital strategy.",
    skills: "Search Engine Optimization, SEM, Web Analytics, Conversion Optimization",
    impact: "Recognized globally across marketing agencies, MNCs, and eCommerce brands.",
  },
  {
    id: "MS-MCP-89421",
    title: "Microsoft Certified Professional (MCP)",
    partner: "Microsoft",
    category: "Global Tech",
    image: microsoftImg,
    fallbackUrl: "https://thirdeyeclasses.com/wp-content/uploads/2024/08/Certificate_MCP-1024x724.jpg",
    issuer: "Microsoft Corporation (Satya Nadella Signatory)",
    description: "Rigorous international credential verifying proficiency in enterprise systems architecture, cloud computing, and developer tech.",
    skills: "Enterprise Architecture, Azure Cloud Systems, C# .NET, Modern DevOps",
    impact: "Industry gold standard for software developers and enterprise systems engineers worldwide.",
  },
  {
    id: "ADOBE-ACA-92841",
    title: "Visual Design using Adobe Photoshop",
    partner: "Adobe",
    category: "Creative & CAD",
    image: adobeImg,
    fallbackUrl: "https://thirdeyeclasses.com/wp-content/uploads/2024/08/Peruna-the-Pony-Adobe-Photoshop-Cert-825x510-1.jpg",
    issuer: "Adobe Systems & Certiport (Shantanu Narayen Signatory)",
    description: "Adobe Certified Associate credential demonstrating industry-standard visual design, digital illustration, and photo compositing.",
    skills: "Adobe Photoshop CC, Color Grading, Digital Compositing, Visual Layout",
    impact: "Required qualification for leading VFX studios, gaming companies, and design agencies.",
  },
  {
    id: "AUTODESK-ATC-4819",
    title: "Autodesk AutoCAD Professional",
    partner: "Autodesk",
    category: "Creative & CAD",
    image: autodeskImg,
    fallbackUrl: "https://thirdeyeclasses.com/wp-content/uploads/2024/08/1.-Autodesk-AutoCAD-Certification.webp",
    issuer: "Autodesk Authorized Training Center",
    description: "Official authorized certification validating professional expertise in precision 2D drafting, architectural plans, and 3D modeling.",
    skills: "AutoCAD 2D Drafting, 3D Spatial Modeling, Isometric Blueprints, CAD Matrix",
    impact: "Standard of competence required by civil, mechanical, architectural, and interior firms.",
  },
  {
    id: "CR-ECC-78192",
    title: "Cybersecurity & IT Network Defense",
    partner: "EC-Council",
    category: "Industry & Hiring",
    image: eccouncilImg,
    fallbackUrl: "https://thirdeyeclasses.com/wp-content/uploads/2024/08/6402684b-7fc8-4a12-aafe-de93446f9ded.png",
    issuer: "EC-Council CodeRed USA",
    description: "Certificate of achievement certifying hands-on tactical ethical hacking, threat hunting, and infrastructure protection.",
    skills: "Network Defense, Vulnerability Assessment, Threat Mitigation, Linux Hardening",
    impact: "Recognized by cybersecurity defense teams and enterprise IT departments worldwide.",
  },
  {
    id: "RHCSA-240-9182",
    title: "Red Hat Certified System Administrator",
    partner: "Red Hat",
    category: "Global Tech",
    image: redhatImg,
    fallbackUrl: "https://thirdeyeclasses.com/wp-content/uploads/2024/08/Nandan_Bhat_RHCSA.png",
    issuer: "Red Hat Inc. Global Examination Board",
    description: "Performance-based credential proving enterprise Linux skills including installation, command-line control, and storage management.",
    skills: "RHEL Administration, Shell Automation, File Systems, Security SELinux",
    impact: "One of the most respected credentials for cloud infrastructure and systems engineering.",
  },
];
